### ISSUE TITLE
Bertha converts URLs in anchor tags by default in Markdown columns.

### ISSUE THREAD

**Issue by izzyblues** [Financial-Times/bertha#28]
If I put 
`FT.com` in a markdown column it will be transformed in
`<p><a href="http://FT.com">FT.com</a><\p>` 
I think that I expect the following result. Isn't it?
`<p>FT.com<\p>`

**Comment by kavanagh** [comment]
This is an issue with GItHub Flavoured Markdown: 

You can html encode the full stop FT&#46;com

https://gist.github.com/alexpeattie/4729247

http://stackoverflow.com/questions/25706012/how-do-i-prevent-auto-generated-links-in-the-github-wiki
